### ISSUE TITLE
unpack requires a bytes object of length 1

### ISSUE THREAD

**Issue by Greenlamp2** [louisabraham/LaBot#10]
Bonjour, lorsque je lance decompile_items.sh, lorsqu'il éxécute ceci:

> python3 "./PyDofus/dlm_unpack.py" "$file"

j'obtiens une ribambelle d'erreur:
![selection_138](https://user-images.githubusercontent.com/44787002/51103680-fb248380-17e3-11e9-8338-9fb5e959c9ba.png)
![selection_139](https://user-images.githubusercontent.com/44787002/51103683-fcee4700-17e3-11e9-9f1b-a395dcfc4e46.png)
Une idée de ce que je dois faire pour résoudre ça ?

merci d'avance

**Comment by Greenlamp2** [comment]
for example, i have this error with this file:

> ./output/maps0.d2p/0/152306690.dlm

[152306690.dlm.zip](https://github.com/louisabraham/LaBot/files/2754591/152306690.dlm.zip)

**Comment by louisabraham** [comment]
Ce code provient de https://github.com/balciseri/PyDofus, ce n'est pas moi qui l'ai écrit.

@ldorigo, des idées ?

**Comment by Greenlamp2** [comment]
ok merci, on peut close l'issue du coup.
