### ISSUE TITLE
Running protocol.py

### ISSUE THREAD

**Issue by MorganBerger** [louisabraham/LaBot#16]
J'obtiens une erreur lorsque j'essaie d'exécuter la commande :
`python3 protocol.py` après avoir décompilé et run `python3 build_protocol.py`

<img width="636" alt="Screenshot 2019-08-02 at 16 07 44" src="https://user-images.githubusercontent.com/5556307/62375918-b671f700-b53f-11e9-9355-cf5da287b6ec.png">

**Comment by louisabraham** [comment]
Bonjour, c'est réglé ?

**Comment by MorganBerger** [comment]
Ce problème là oui ! 
J'ai pu lance le script avec la commande `python3 -m labot.protocol`
Cependant j'ai un peu de mal à savoir comment run des commandes in-game, je n'ai pas d'erreur d'exécution mais rien ne se passe lorsque j'essaie, et zéro réaction dans mon term.
Dans la doc, tu as marqué "Démarrage d'un bot, avec possibilité de lancer les callbacks en asynchrone". Est-ce que le bot est inclus au projet ou bien faut-il le coder soit même ? 
Merci

**Comment by louisabraham** [comment]
Il faut envoyer toi-même les paquets. LaBot gère le protocole, mais il faut que tu lui dises quoi faire.
