### ISSUE TITLE
Problème d'installation du sniffer

### ISSUE THREAD

**Issue by 6Neotix9** [louisabraham/LaBot#27]
**Bonjour,**
j'ai commencé à essayer de décrypter les packet de dofus. Je me suis très vite retrouver face à un mur à cause de flash.
J'ai donc décider d'utilisé ton sniffer pour pour décrypter les packet automatique mais je n'arrive pas à le mettre en place.
Je ne sait pas si c'est juste moi qui est juste une bille en linux et python ou si c'est le read.md qui n'est pas à jour.

Tout d'abord j'utilise decompile.sh en ayant modifier les chemin du jeu et de FFDec. Tout marche nickel.
Ensuite je lance build_protocol.py qui se trouve toujours dans le dossier script. Tout marche nickel il fait bien le fichier protocol.pk
C'est en suite pour protocol.py que j'ai des problèmes. Le seul endroit où il se trouve est dans le dossier labot. Lorsque je le lance il m'indique l'érreur. :
`Traceback (most recent call last):
  File "/home/neo/Bureau/LaBot-master/labot/protocol.py", line 6, in <module>
    from .protocol_load import types, msg_from_id, types_from_id, primitives
ImportError: attempted relative import with no known parent package
`
Lorsque je lance ensuite la commande `sudo python -m labot.sniffer.main` celle-ci renvoie :
`/usr/bin/python3: Error while finding module specification for 'labot.sniffer.main' (ModuleNotFoundError: No module named 'labot')
`
Je serais très reconnaissant si tu pouvait m'aider.

**Comment by kenny94xxhell** [comment]
Hello, 
Je ne sais pas si LaBot est toujours dans les parages, ça commence à dater...
As tu vérifier que le protokol.pk généré pèse bien plus que 1 octet ?
Si le build_protocol.py plante, il ne te le dis pas forcément et il crée un protokol.pk vide.

**Comment by 6Neotix9** [comment]
Bonjour,
j'ai pu régler le problème grâce au autres rapports d'erreurs.
Par contre je n'ai pas exactement compris comment peut-on récupérer les objets msg sur un autre programmes en python (mon bot). 
Je ne sait pas si il faut faire directement `import labot` puit le démarrer le module en assync sur mon programme ou si une meilleur procédure est prévu.

**Comment by kenny94xxhell** [comment]
Dans ton script perso, tu peux lancer le sniffer comme ça (au détail près si l'arborescence à changé depuis)
```Python
from LaBot.labot.sniffer import __main__
from LaBot.labot.sniffer import network
```

**Comment by 6Neotix9** [comment]
Je fait comment après pour récupérer les packet sans passer par l'interface web justement ? En soit je peut automatiser un navigateur mais c'est vraiment pas optimiser.
Est ce qu'on doit essayer de récupérer l'objet msg dans le module network ou est qu'il y a un moyen de récupérer les packets sur localhost:8888 sans passer par l'interface ?

**Comment by kenny94xxhell** [comment]
De mémoire je me servais du mitm pour sniffer. Le sniffer ne fonctionne qu'avec l'interface web

**Comment by 6Neotix9** [comment]
ok merci

**Comment by louisabraham** [comment]
@Neo-jv hésite pas à améliorer le README si tu veux :)

Merci pour l'aide @kenny94xxhell :)
