### ISSUE TITLE
Sniffer on Win : 'PcapTimeoutElapsed' is not defined

### ISSUE THREAD

**Issue by jchenaud** [louisabraham/LaBot#31]
NameError: name 'PcapTimeoutElapsed' is not defined

impossible de le faire fonctionner sur win

mon Install de scapy semble bonne mais  ne contient pas   scapy.arch.pcapdnet   donc pas PcapTimeoutElapsed

**Comment by louisabraham** [comment]
Je n'ai plus le temps de maintenir le sniffer.

Tu peux essayer de remplacer
```py
        from scapy.arch.pcapdnet import PcapTimeoutElapsed

        read_allowed_exceptions = (PcapTimeoutElapsed,)
```
par
```py
        read_allowed_exceptions = ()
```

et voir si tu as des erreurs!
