### ISSUE TITLE
Data is never parsed : got message id but no content

### ISSUE THREAD

**Issue by Spaicho** [louisabraham/LaBot#8]
Hi, first of all great work.
I'm facing an issue regarding message parsing : id is identified but data is never parsed.
Is it normal ? 

below is the debug logs :

  02:01:35.662 DEBUG: Thread-2 - network.on_receive(): Received packet.  

02:01:35.662 DEBUG: Thread-2 - network.from_client(): Determining packet origin... 

02:01:35.662 DEBUG: Thread-2 - network.from_client(): Packet comes from local machine 

02:01:35.662 DEBUG: Thread-2 - msg.fromRaw(): Trying to parse message from raw buffer... 

02:01:35.662 DEBUG: Thread-2 - msg.fromRaw(): Message has id 952 

02:01:35.662 DEBUG: Thread-2 - msg.fromRaw(): Parsed message with ID 952 

02:01:35.663 DEBUG: Thread-2 - msg.__init__(): Initialized Msg with id 952 

02:01:35.663 DEBUG: Thread-2 - ui.appendMsg(): Adding message to table 

02:01:35.663 DEBUG: Thread-2 - ui.__init__(): Initializing UI Msg: GameMapMovementConfirmMessage 

02:01:35.665 DEBUG: Thread-2 - msg.fromRaw(): Trying to parse message from raw buffer... 

02:01:35.665 DEBUG: Thread-2 - msg.fromRaw(): Could not parse message: Not complete 

02:01:35.710 DEBUG: Thread-2 - network.on_receive(): Received packet.  

02:01:35.710 DEBUG: Thread-2 - network.from_client(): Determining packet origin... 

02:01:35.711 DEBUG: Thread-2 - network.from_client(): Packet comes from server

**Comment by louisabraham** [comment]
The most probable explanation is that the protocol builder failed.
Look manually at the source code of the deserialize method for this packet and compare it with the corresponding value of `types_from_id`.

I can look at the problem in a few days, but could you attach a dump of the packet?

**Comment by louisabraham** [comment]
Hi, do you still get this issue?

**Comment by louisabraham** [comment]
There were major updates in the code base during the last week. I'm closing this from now, please reopen if you still have the issue.
